job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-netherlands
    APP_HOSTPATH: nl
    WP_DB_NAME_PREFIX: planet4-nl_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: netherlands
    HELM_RELEASE: planet4-netherlands
    WP_DB_NAME: planet4-nl_wordpress_develop
    WP_STATELESS_BUCKET: planet4-netherlands-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: netherlands-staging
    HELM_RELEASE: planet4-netherlands-release
    WP_DB_NAME: planet4-nl_wordpress_release
    WP_STATELESS_BUCKET: planet4-netherlands-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: netherlands
    HELM_RELEASE: planet4-netherlands-master
    MIN_REPLICA_COUNT: 2
    WP_DB_NAME: planet4-nl_wordpress_master
    WP_STATELESS_BUCKET: planet4-netherlands-stateless
